### ISSUE TITLE
npx cdk bootstrap works but npx cdk deploy FAILS

### ISSUE THREAD

**Issue by rickthedevil** [aws-samples/apollo-server-on-aws-lambda#5]
Bundling asset ApolloLambdaWebsocketStack/ConnectionHandler/ConnectionHandler/Code/Stage...
npm ERR! canceled

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/rickross/.npm/_logs/2023-12-17T19_47_30_666Z-debug.log
/Users/rickross/apollo-server-on-aws-lambda/cdk/node_modules/@aws-cdk/core/lib/asset-staging.ts:398
      throw new Error(`Failed to bundle asset ${this.node.path}, bundle output is located at ${bundleErrorDir}: ${err}`);
            ^
Error: Failed to bundle asset ApolloLambdaWebsocketStack/ConnectionHandler/ConnectionHandler/Code/Stage, bundle output is located at /Users/rickross/apollo-server-on-aws-lambda/cdk/cdk.out/bundling-temp-bb4be2f356ae6c255f5178df453a9790383b2acc9c7825921664c5360339deb5-error: Error: bash exited with status 1
    at AssetStaging.bundle (/Users/rickross/apollo-server-on-aws-lambda/cdk/node_modules/@aws-cdk/core/lib/asset-staging.ts:398:13)
    at AssetStaging.stageByBundling (/Users/rickross/apollo-server-on-aws-lambda/cdk/node_modules/@aws-cdk/core/lib/asset-staging.ts:246:10)
    at stageThisAsset (/Users/rickross/apollo-server-on-aws-lambda/cdk/node_modules/@aws-cdk/core/lib/asset-staging.ts:137:35)
    at Cache.obtain (/Users/rickross/apollo-server-on-aws-lambda/cdk/node_modules/@aws-cdk/core/lib/private/cache.ts:24:13)
    at new AssetStaging (/Users/rickross/apollo-server-on-aws-lambda/cdk/node_modules/@aws-cdk/core/lib/asset-staging.ts:162:44)
    at new Asset (/Users/rickross/apollo-server-on-aws-lambda/cdk/node_modules/@aws-cdk/aws-s3-assets/lib/asset.ts:68:21)
    at AssetCode.bind (/Users/rickross/apollo-server-on-aws-lambda/cdk/node_modules/@aws-cdk/aws-lambda/lib/code.ts:183:20)
    at new Function (/Users/rickross/apollo-server-on-aws-lambda/cdk/node_modules/@aws-cdk/aws-lambda/lib/function.ts:331:29)
    at new NodejsFunction (/Users/rickross/apollo-server-on-aws-lambda/cdk/node_modules/@aws-cdk/aws-lambda-nodejs/lib/function.ts:51:5)
    at new SimpleLambda (/Users/rickross/apollo-server-on-aws-lambda/cdk/lib/apollo-lambda-websocket-stack.ts:36:15)
Subprocess exited with error 1

**Comment by rickthedevil** [comment]
> Bundling asset ApolloLambdaWebsocketStack/ConnectionHandler/ConnectionHandler/Code/Stage... npm ERR! canceled
> 
> npm ERR! A complete log of this run can be found in: npm ERR! /Users/rickross/.npm/_logs/2023-12-17T19_47_30_666Z-debug.log /Users/rickross/apollo-server-on-aws-lambda/cdk/node_modules/@aws-cdk/core/lib/asset-staging.ts:398 throw new Error(`Failed to bundle asset ${this.node.path}, bundle output is located at ${bundleErrorDir}: ${err}`); ^ Error: Failed to bundle asset ApolloLambdaWebsocketStack/ConnectionHandler/ConnectionHandler/Code/Stage, bundle output is located at /Users/rickross/apollo-server-on-aws-lambda/cdk/cdk.out/bundling-temp-bb4be2f356ae6c255f5178df453a9790383b2acc9c7825921664c5360339deb5-error: Error: bash exited with status 1 at AssetStaging.bundle (/Users/rickross/apollo-server-on-aws-lambda/cdk/node_modules/@aws-cdk/core/lib/asset-staging.ts:398:13) at AssetStaging.stageByBundling (/Users/rickross/apollo-server-on-aws-lambda/cdk/node_modules/@aws-cdk/core/lib/asset-staging.ts:246:10) at stageThisAsset (/Users/rickross/apollo-server-on-aws-lambda/cdk/node_modules/@aws-cdk/core/lib/asset-staging.ts:137:35) at Cache.obtain (/Users/rickross/apollo-server-on-aws-lambda/cdk/node_modules/@aws-cdk/core/lib/private/cache.ts:24:13) at new AssetStaging (/Users/rickross/apollo-server-on-aws-lambda/cdk/node_modules/@aws-cdk/core/lib/asset-staging.ts:162:44) at new Asset (/Users/rickross/apollo-server-on-aws-lambda/cdk/node_modules/@aws-cdk/aws-s3-assets/lib/asset.ts:68:21) at AssetCode.bind (/Users/rickross/apollo-server-on-aws-lambda/cdk/node_modules/@aws-cdk/aws-lambda/lib/code.ts:183:20) at new Function (/Users/rickross/apollo-server-on-aws-lambda/cdk/node_modules/@aws-cdk/aws-lambda/lib/function.ts:331:29) at new NodejsFunction (/Users/rickross/apollo-server-on-aws-lambda/cdk/node_modules/@aws-cdk/aws-lambda-nodejs/lib/function.ts:51:5) at new SimpleLambda (/Users/rickross/apollo-server-on-aws-lambda/cdk/lib/apollo-lambda-websocket-stack.ts:36:15) Subprocess exited with error 1

This issue was due to the difference between the runtime environments between the CDK and the nodejs de environment. Solved now.
